openapi: "3.0.3"
tags:
  - name: Swaggers

info:
  title: Swaggipedia - Api Catalog
  description: Api Catalog
  version: "1.0.0"

paths:
  # Swaggers
  /v1/swaggers:
    get:
      parameters:
        - in: query
          name: expand
          description: a parameter for including swagger file content to the response swaggers list
          schema:
            type: string
            enum: ["file_content"]
      tags:
        - Swaggers
      summary: Get All Swaggers
      description: Get all swaggers (APIs) of the API-Catalog
      operationId: getSwaggers
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SwaggerResource"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - Swaggers
      summary: Create Swagger
      description: Add swagger to the API-Catalog
      operationId: createSwagger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SwaggerPostRequest"
      responses:
        201:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SwaggerResource"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
  /v1/swaggers/{swagger_id}:
    parameters:
      - name: swagger_id
        in: path
        description: The required swagger id
        required: true
        schema:
          $ref: "#/components/schemas/SwaggerId"
    get:
      tags:
        - Swaggers
      summary: Get Swagger
      description: Get a swagger in the API-Catalog
      operationId: getSwagger
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SwaggerResource"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - Swaggers
      summary: Update Swagger
      description: Update a swagger in the API-Catalog
      operationId: updateSwagger
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SwaggerPutRequest"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SwaggerResource"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
    delete:
      tags:
        - Swaggers
      summary: Delete Swagger
      description: delete a swagger from the API-Catalog
      operationId: deleteSwagger
      responses:
        204:
          description: "Invalidated"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    NoContent:
      description: No Content.

    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    NotFound:
      description: Not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Conflict:
      description: Conflict.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      required:
        - message
      properties:
        more_info:
          type: string
          description: More info about the error.
          minLength: 1
          maxLength: 5000
        message:
          type: string
          minLength: 1
          maxLength: 2000
        category:
          type: string
          minLength: 1
          maxLength: 1000

    SwaggerId:
      description: "The swagger uuid"
      type: string
      pattern: "^[0-9A-Fa-f]{8}[-]?([0-9A-Fa-f]{4}[-]?){3}[0-9A-Fa-f]{12}$"
      example: 287d6dff-069b-47d0-8b7b-248c3399b8c4

    CreatedAt:
      description: "The time the object was created"
      type: string
      format: date-time
      example: "2020-05-20T00:00:00Z"
      readOnly: true

    UpdatedAt:
      description: "The time the object was created"
      type: string
      format: date-time
      example: "2020-05-20T00:00:00Z"
      readOnly: true

    SwaggerTitle:
      description: "The swagger title"
      type: string
      minLength: 1
      maxLength: 1000

    SwaggerAliases:
      description: "The swagger title"
      type: array
      items:
        type: string
        minLength: 1
        maxLength: 20

    SwaggerRepositoryUrl:
      description: "The repository url contains the swagger file"
      type: string
      minLength: 1
      maxLength: 1000

    SwaggerSourceFilePath:
      description: "The repository path to the swagger source file"
      type: string
      minLength: 1
      maxLength: 1000

    SwaggerData:
      description: "The swagger content"
      type: string
      minLength: 1

    SwaggerPostRequest:
      type: object
      required:
        - title
        - file_content
        - repository_url
      additionalProperties: false
      properties:
        title:
          $ref: "#/components/schemas/SwaggerTitle"
        aliases:
          $ref: "#/components/schemas/SwaggerAliases"
        file_content:
          $ref: "#/components/schemas/SwaggerData"
        repository_url:
          $ref: "#/components/schemas/SwaggerRepositoryUrl"
        file_source_path:
          $ref: "#/components/schemas/SwaggerSourceFilePath"

    SwaggerPutRequest:
      type: object
      additionalProperties: false
      properties:
        title:
          $ref: "#/components/schemas/SwaggerTitle"
        aliases:
          $ref: "#/components/schemas/SwaggerAliases"
        file_content:
          $ref: "#/components/schemas/SwaggerData"
        repository_url:
          $ref: "#/components/schemas/SwaggerRepositoryUrl"
        file_source_path:
          $ref: "#/components/schemas/SwaggerSourceFilePath"

    SwaggerResource:
      type: object
      required:
        - id
        - title
        - file_content
        - repository_url
        - file_source_path
        - created_at
        - updated_at
      additionalProperties: false
      properties:
        id:
          $ref: "#/components/schemas/SwaggerId"
        title:
          $ref: "#/components/schemas/SwaggerTitle"
        aliases:
          $ref: "#/components/schemas/SwaggerAliases"
        file_content:
          $ref: "#/components/schemas/SwaggerData"
        repository_url:
          $ref: "#/components/schemas/SwaggerRepositoryUrl"
        file_source_path:
          $ref: "#/components/schemas/SwaggerSourceFilePath"
        created_at:
          $ref: "#/components/schemas/CreatedAt"
        updated_at:
          $ref: "#/components/schemas/UpdatedAt"
